# This compose file is only for local testing

services:
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine@sha256:7632f0bf559e4640f1f532bf10eaac8857d016a383d5e73f46a23db0431e8c8a
    restart: unless-stopped
    # we need a persistent hostname ensure rabbitmq keeps using the same storage
    hostname: rabbitmq
    ports:
      - 127.0.0.1:15672:15672
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  inbox-receiver:
    image: ghcr.io/nothing4you/activitypub-federation-queue-batcher/inbox-receiver:local
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      LOGLEVEL: debug
      RABBITMQ_HOSTNAME: rabbitmq

  batch-sender:
    image: ghcr.io/nothing4you/activitypub-federation-queue-batcher/batch-sender:local
    restart: unless-stopped
    environment:
      LOGLEVEL: debug
      RABBITMQ_HOSTNAME: rabbitmq
      BATCH_RECEIVER_PROTOCOL: http
      BATCH_RECEIVER_DOMAIN: batch-receiver:8080
      BATCH_RECEIVER_PATH: /batch

  batch-receiver:
    image: ghcr.io/nothing4you/activitypub-federation-queue-batcher/batch-receiver:local
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      LOGLEVEL: debug
      BATCH_RECEIVER_PATH: /batch
      OVERRIDE_DESTINATION_PROTOCOL: http
      # OVERRIDE_DESTINATION_DOMAIN: lemmy:8080
      OVERRIDE_DESTINATION_DOMAIN: nginx

  nginx:
    image: nginx@sha256:d2cb0992f098fb075674730da5e1c6cccdd4890516e448a1db96e0245c1b7fca
    restart: unless-stopped
